DELETED = 'deleted'
ADDED = 'added'
UNCHANGED = 'unchanged'
CHANGED = 'changed'
NESTED = 'nested'
NEW = '+'
OLD = '-'
NOCHANGE = ' '
NUMBER_OF_SPACES = 4
SPACE = ' '
TEMPLATE_STYLISH = '{0}{1} {2}: {3}'
TEMPLATE_ADDED = "Property '{0}' was added with value: {1}"
TEMPLATE_REMOVED = "Property '{0}' was removed"
TEMPLATE_UPDATED = "Property '{0}' was updated. From {1} to {2}"
